### ISSUE TITLE
[ERROR] FATAL UNHANDLED EXCEPTION escape from level 4

### ISSUE THREAD

**Issue by holten** [quill18/ld36#1]
bug report!

wall breached north of the corridor at Line 109 in FloorMaps.cs
moving through the rubble
escaping to the void

```
                                                                  ║                
                                    @                             ║                
░░░░░░░░░░░░░░░░░░░      #######x   #############    ░░░░░░░░░░║                
░░░░░                     #x      #x#xx           #    ░░░░░░░░░░║                
░░░░                     #x                       #####░░░░░░░░░░║
```

(some irrelevant room elements removed from the illo)

> Unhandled Exception:  
> System.NullReferenceException: Object reference not set to an instance of an object
>   at LD36Quill18.PlayerCharacter.MoveTo (Int32 newX, Int32 newY) <0x17cfa28 + 0x0002d> in <filename unknown>:0 
>   at LD36Quill18.Character.MoveBy (Int32 dX, Int32 dY) <0x17cf9f0 + 0x00025> in <filename unknown>:0 
>   at LD36Quill18.PlayerCharacter.Update () <0x17cf908 + 0x00087> in <filename unknown>:0 
>   at LD36Quill18.Floor.Update (Boolean doTick) <0x17cb580 + 0x00082> in <filename unknown>:0 
>   at LD36Quill18.Game.Update () <0x17caf98 + 0x000a3> in <filename unknown>:0 
>   at LD36Quill18.MainClass.RunGame () <0x14b2ea8 + 0x00087> in <filename unknown>:0 
>   at LD36Quill18.MainClass.Main (System.String[] args) <0x1400f58 + 0x00027> in <filename unknown>:0

suggested fix: plug the hole

**Comment by holten** [comment]
Uh. Turns out I was playing one of the prerelease versions from before the debris was made impassable. I thought I had the final build, but no. Sorry.

**Comment by quill18** [comment]
I'm happy you cared enough to try to fix the problem!
